name: Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose: plan | apply | destroy"
        required: true
        default: "plan"
  pull_request:
  push:
    branches: [ "main" ]

concurrency:
  group: tf-aws-lab-eu-west-2
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::915227021404:role/GitHubActionsTerraformRole
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Debug checkout SHA and key line
        run: |
          echo "Checked out SHA: $(git rev-parse HEAD)"
          grep -n "public_key" -n main.tf
          ls -la id_ed25519.pub || true
      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Plan
        if: github.event_name != 'workflow_dispatch' || github.event.inputs.action == 'plan'
        run: terraform plan

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve
